### PR TITLE
Get transactionReference from current request

### PR DESCRIPTION
**Pull request by barryvdh**
Instead of transactionId, because trxid is the transactionReference instead of transactionId, in Omnipay context.
Fixes #1

### CODE REVIEW

**Comment by aderuwe** [comment]
:+1:

**Comment by amacneil** [comment]
Looks good. FYI in future you can simply push additional commits, or force push new commits to your existing branch to update a PR.

**Comment by amacneil** [comment]
Speaking of which, can you squash these changes to a single commit and force push? Otherwise I'll merge this when I'm back at my computer.

**Comment by barryvdh** [comment]
Yeah I tried doing that, I sent another commit to patch-1, but it didn't get picked up by the PR. Perhaps because it was already closed.
But I squashed the commits, hope this is better.

**Comment by amacneil** [comment]
:+1: thanks

**Comment by barryvdh** [comment]
Thanks :) Can you also tag a new release?

**Comment by amacneil** [comment]
Done :)

**Pull request merged**
